In [2]:
import pandas as pd
import matplotlib as plt

In [42]:
df=pd.read_csv("health dataset.csv")
df.head()

,Age,Gender,BMI,Blood Pressure,FBS,HbA1c,Family History of Diabetes,Smoking,Diet,Exercise,Diagnosis
0,45,Male,25,Normal,100,5.7,No,No,Healthy,Regular,No
1,55,Female,30,High,120,6.4,Yes,Yes,Poor,No,Yes
2,65,Male,35,High,140,7.1,Yes,Yes,Poor,No,Yes
3,75,Female,40,High,160,7.8,Yes,Yes,Poor,No,Yes
4,40,Male,20,Normal,80,5.0,No,No,Healthy,Regular,No

Checking whether there are null values.

In [16]:
print("Null values:")
df.isnull().sum()

Null values:

Age                           0
Gender                        0
BMI                           0
Blood Pressure                0
FBS                           0
HbA1c                         0
Family History of Diabetes    0
Smoking                       0
Diet                          0
Exercise                      0
Diagnosis                     0
dtype: int64

In [23]:
df.nunique()

Age                           35
Gender                         2
BMI                           34
Blood Pressure                 3
FBS                           11
HbA1c                         11
Family History of Diabetes     2
Smoking                        2
Diet                           2
Exercise                       2
Diagnosis                      2
dtype: int64

We can see that columns like Gender, Family History of Diabetes, Smoking, Diet, Exercise,Diagnosis can be easily transformed into binary values so that our model can process the data.

In [43]:
df["Gender"]=df["Gender"].map({"Male": 0, "Female": 1})

yes_no={"No":0, "Yes": 1}
for col in ["Diagnosis", "Smoking","Family History of Diabetes" ]:
    df[col]=df[col].map(yes_no)

df.head() #checking values

,Age,Gender,BMI,Blood Pressure,FBS,HbA1c,Family History of Diabetes,Smoking,Diet,Exercise,Diagnosis
0,45,0,25,Normal,100,5.7,0,0,Healthy,Regular,0
1,55,1,30,High,120,6.4,1,1,Poor,No,1
2,65,0,35,High,140,7.1,1,1,Poor,No,1
3,75,1,40,High,160,7.8,1,1,Poor,No,1
4,40,0,20,Normal,80,5.0,0,0,Healthy,Regular,0

In [ ]:
df["Diet"]=(df["Diet"]=="Healthy").astype(int)
df["Exercise"]=(df["Exercise"]=="Regular").astype(int)
df.head() #also checking

,Age,Gender,BMI,Blood Pressure,FBS,HbA1c,Family History of Diabetes,Smoking,Diet,Exercise,Diagnosis
0,45,0,25,Normal,100,5.7,0,0,1,1,0
1,55,1,30,High,120,6.4,1,1,0,0,1
2,65,0,35,High,140,7.1,1,1,0,0,1
3,75,1,40,High,160,7.8,1,1,0,0,1
4,40,0,20,Normal,80,5.0,0,0,1,1,0

When it comes to Blood Pressure I decided to use